config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "executie#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/executie.rb
class Executie < ApplicationRecord

#belongs_to :town


# define ActiveRecord scopes for
# :search_query, :sorted_by, :with_country_id, and :with_created_at_gte
end

app/models/town.rb
class Town < ApplicationRecord

	#has_many :executies
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/executie_controller.rb
class ExecutieController < ApplicationController

	def index
	   @executii = Executie.all 	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/executie_helper.rb
module ExecutieHelper
end

app/views/executie/_form.html.erb
<%= form_for @executie, :html => { :class => "form-horizontal executie" } do |f| %>

  <% if @executie.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@executie.errors.count, "error") %> prohibited this executie from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @executie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :tv, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tv, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tv) %>
  </div>
  <div class="form-group">
    <%= f.label :tc, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tc) %>
  </div>
  <div class="form-group">
    <%= f.label :month, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :month, :class => 'form-control' %>
    </div>
    <%=f.error_span(:month) %>
  </div>
  <div class="form-group">
    <%= f.label :tip, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tip, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tip) %>
  </div>
  <div class="form-group">
    <%= f.label :sursa, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sursa, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sursa) %>
  </div>
  <div class="form-group">
    <%= f.label :funct_code_class, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :funct_code_class, :class => 'form-control' %>
    </div>
    <%=f.error_span(:funct_code_class) %>
  </div>
  <div class="form-group">
    <%= f.label :func_desc, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :func_desc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:func_desc) %>
  </div>
  <div class="form-group">
    <%= f.label :eco_code_class, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :eco_code_class, :class => 'form-control' %>
    </div>
    <%=f.error_span(:eco_code_class) %>
  </div>
  <div class="form-group">
    <%= f.label :eco_desc, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :eco_desc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:eco_desc) %>
  </div>
  <div class="form-group">
    <%= f.label :exec_cumul, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :exec_cumul, :class => 'form-control' %>
    </div>
    <%=f.error_span(:exec_cumul) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                executies_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/executie/_list.html.erb
<div id="filterrific_results">

  <div>
    <%= page_entries_info executies # provided by will_paginate %>
  </div>

  <table>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Country</th>
      <th>Registered at</th>
    </tr>
    <% executies.each do |executie| %>
      <tr>
        <td><%= #link_to executie.full_name, executie_path executie)) %></td>
        <td><%= executie.tip %></td>
        <td><%= executie.month %></td>
        <td><%= executie.func_desc %></td>
        <td><%= executie.exec_cumul %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= will_paginate executies # provided by will_paginate %>

app/views/executie/edit.html.erb
<%- model_class = Executie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/executie/index.html.erb
<!DOCTYPE html>
<html>
<head>  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" lang="ro">

  <title>Execuții Bugetare Detaliate</title>
</head>

  <div class="container">
<body>


    
<div class="well">
  <h4>Execuții Bugetare Detaliate | 2016: Oraș Hârlău, Județul Iași</h4>
</div><br>
<hr>
  <table id='execs' class='table'>
   <thead>
      <tr>
      <th>Lună</th>
      <th width='10%'>Tip</th>
      <th>Descriere Funcțională </th>
      <th>Clasificație Funcțională</th>
    <!--  <th>Descriere Economică</th> -->
      <th>Clasificare Economică</th>
    
      <th>Total</th>
    </tr>
   </thead>
   <tbody>
  <% @executii.each do |e| %>
    
      <tr>
      <td><%= e.month %> </td>
      <td><%= e.tip %> </td>
      <td> <%=  e.func_desc  %></td>
      <td><%= e.funct_code_class %> </td>
  
      <td> <%= e.eco_code_class %> </td>
     
      <td><%= number_to_currency(e.exec_cumul, unit: "RON", separator: ",", delimiter: "", format: "%n %u") %> </td>
    </tr>  
    <% end %>
      </tbody>
  </table>

</body>

<footer>
<div class="well well-sm">
  <p>Bogdan Arsene</p> <br>
  <p>Sursă Date: <a href="http://www.transparenta-bugetara.gov.ro/transparenta-bugetara/index.htm">Transparență-Bugetară .gov.ro</a></p>
</div>
  </div>
  
</footer>


</html>

app/views/executie/new.html.erb
<%- model_class = Executie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/executie/show.html.erb
<%- model_class = Executie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tv) %>:</strong></dt>
  <dd><%= @executie.tv %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tc) %>:</strong></dt>
  <dd><%= @executie.tc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:month) %>:</strong></dt>
  <dd><%= @executie.month %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tip) %>:</strong></dt>
  <dd><%= @executie.tip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sursa) %>:</strong></dt>
  <dd><%= @executie.sursa %></dd>
  <dt><strong><%= model_class.human_attribute_name(:funct_code_class) %>:</strong></dt>
  <dd><%= @executie.funct_code_class %></dd>
  <dt><strong><%= model_class.human_attribute_name(:func_desc) %>:</strong></dt>
  <dd><%= @executie.func_desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:eco_code_class) %>:</strong></dt>
  <dd><%= @executie.eco_code_class %></dd>
  <dt><strong><%= model_class.human_attribute_name(:eco_desc) %>:</strong></dt>
  <dd><%= @executie.eco_desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:exec_cumul) %>:</strong></dt>
  <dd><%= @executie.exec_cumul %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              executies_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_executy_path(@executie), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              executy_path(@executie),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Applied</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>